services:
  # Webサービス定義
  - type: web
    name: golf-ai-strategist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 'app:create_app()'
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: PRODUCTION
        value: "true"
      - key: PERPLEXITY_MODEL
        value: "sonar-pro"
      - key: DATABASE_URL
        fromDatabase:
          name: golf-db
          property: connectionString
      - key: USE_GOOGLE_DRIVE
        value: "true"
      - key: GOOGLE_DRIVE_CREDENTIALS
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
    autoDeploy: true
    healthCheckPath: /

  # データベース定義
  databases:          # ← 新しいセクション
    - name: golf-db
      plan: free      # 30 日制限・1 GB 上限に注意
      postgresMajorVersion: "16"
      diskSizeGB: 1   # 省略可
